"""Sync after manual hash_value addition

Revision ID: 1afe446d00e7
Revises: 4bcd3aa1324b
Create Date: 2025-06-15 04:11:28.111343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1afe446d00e7'
down_revision = '4bcd3aa1324b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_value', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_column('hash_value')

    # ### end Alembic commands ###
