"""Initial migration

Revision ID: 4bcd3aa1324b
Revises: 
Create Date: 2025-06-15 03:55:38.881753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4bcd3aa1324b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.Unicode(length=100), nullable=False),
    sa.Column('subsection_name', sa.Unicode(length=100), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('extension', sa.String(length=4), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    sa.UniqueConstraint('phone', 'extension', name='unique_phone_extension'),
    sa.UniqueConstraint('section_name', 'subsection_name', name='unique_section_subsection')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('courses',
    sa.Column('course_number', sa.Integer(), nullable=False),
    sa.Column('category', sa.Unicode(length=50), nullable=True),
    sa.Column('max_attendance', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('signup_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signup_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('course_start', sa.Date(), nullable=False),
    sa.Column('course_end', sa.Date(), nullable=False),
    sa.Column('hours', mysql.TINYINT(unsigned=True), nullable=False),
    sa.Column('location', sa.Unicode(length=100), nullable=False),
    sa.Column('title', sa.Unicode(length=100), nullable=False),
    sa.Column('intro', sa.UnicodeText(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('course_number')
    )
    op.create_table('users',
    sa.Column('employee_number', sa.String(length=16), nullable=False),
    sa.Column('account', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.Unicode(length=50), nullable=False),
    sa.Column('id_card', sa.CHAR(length=10), nullable=False),
    sa.Column('sex', sa.Enum('男', '女'), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.CHAR(length=10), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('employee_number'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_card'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('applications',
    sa.Column('application_number', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=16), nullable=False),
    sa.Column('course_number', sa.Integer(), nullable=False),
    sa.Column('sign_in_state', sa.Boolean(), nullable=False),
    sa.Column('sign_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_number'], ['courses.course_number'], ),
    sa.ForeignKeyConstraint(['employee_number'], ['users.employee_number'], ),
    sa.PrimaryKeyConstraint('application_number'),
    sa.UniqueConstraint('employee_number', 'course_number', name='unique_user_course')
    )
    op.create_table('certifications',
    sa.Column('certification_id', sa.Integer(), nullable=False),
    sa.Column('certification_code', sa.String(length=50), nullable=True),
    sa.Column('employee_number', sa.String(length=16), nullable=False),
    sa.Column('course_number', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('hash_value', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['course_number'], ['courses.course_number'], ),
    sa.ForeignKeyConstraint(['employee_number'], ['users.employee_number'], ),
    sa.PrimaryKeyConstraint('certification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certifications')
    op.drop_table('applications')
    op.drop_table('users')
    op.drop_table('courses')
    op.drop_table('roles')
    op.drop_table('departments')
    # ### end Alembic commands ###
